#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

./node_modules/.bin/eslint --fix "**/*.js"
./node_modules/.bin/eslint --fix "**/*.ts"
./node_modules/.bin/eslint --fix "**/*.jsx"
./node_modules/.bin/eslint --fix "**/*.tsx"